### ISSUE TITLE
Plugin typescript type

### ISSUE THREAD

**Issue by canadaduane** [chef-js/core#1]
What an incredible project this is! Thanks for packaging it and offering it as something worthy of sharing.

I'm trying to create my first plugin, and I realized I don't know what type the function signature has. I'm using chef-uws, so I guess the `ws` variable is a uWS_Socket type; and the `{ id, event, data }` tuple types are needed also. Here is what I'm copy/pasting/adapting into my server:

```
type WSProp = ((...args: any[]) => any) | any | any[];

export type WSSocket = {
  [prop: string]: WSProp;
};

export type WSEvent = {
  id: string;
  event: string;
  data?: any;
};
export type WSPlugin = (ws: WSSocket, event: WSEvent) => void;
```

Should `WSPlugin` be exported, perhaps by both chef-core and chef-uws?

```
const shelfMergePlugin = function (ws, { id, event, data }) {
  // broadcast to all sockets inside this topic
  this.to("shelf").emit(event, id, data);
};
```

Edit: I also notice that `this` has no type within the `WSPlugin` signature. So far, all I know about "this" is we can call "to('chat')" function on it.

**Comment by nenjack** [comment]
It should be correctly exported

See

```
import { WSPlugin } from "chef-core";
```

I will add this to docs shortly

**Comment by nenjack** [comment]
The type of `this` in such context is typeof this api:

```
  // common `this.to(topic).emit(event, id, data)` api
  const api: object = {
    to: (topic: string) => ({
      emit: (event: string, id: string, data?: any) => {
        server.publish(topic, JSON.stringify({ event, id, data }));
      },
    }),
  };
```

**Comment by nenjack** [comment]
and it's in case of

- uWS flavor - just the above
- socket.io flavor - the socket.io server instance

**Comment by nenjack** [comment]
and actually I've now renamed the types not to have WS to be more intuitive

bumped major version because of this breaking change

> The type of this in such context is typeof this api:

Now that is ServerContext type, and plugin is just Plugin

**Comment by nenjack** [comment]
also see https://chef-js.github.io/core/

now the types should be exported correctly

**Comment by nenjack** [comment]
closing as I checked and I also assume this worked on your end too
