### ISSUE TITLE
Can the cache be disabled?

### ISSUE THREAD

**Issue by canadaduane** [chef-js/core#2]
I'd like to turn off the cache during local development.

I set `maxCacheSize` to 0, but received the following error:

```
Started uws app on port 4200
with plugin(s) shelf
/home/duane/Projects/credit/node_modules/.pnpm/latermom@2.0.1/node_modules/latermom/index.js:39
            const [keyToRemove] = this.data.entries().next().value;
                                  ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Cache.get (/home/duane/Projects/credit/node_modules/.pnpm/latermom@2.0.1/node_modules/latermom/index.js:39:35)
    at /home/duane/Projects/credit/node_modules/.pnpm/chef-uws@1.4.0/node_modules/chef-uws/dist/server/index.js:101:52

Node.js v18.16.0
```

Is there another way to turn off the cache, so that static files that have changed will be reloaded every time from disk?

**Comment by nenjack** [comment]
since latest 2.0.0 version of `core`

and 1.5.0 versions for "flavor" repositories - since they use 2.0.1

just use maxCacheSize = 0

**Comment by canadaduane** [comment]
Thanks! You made so many awesome improvements, I'm still catching up :)

**Comment by nenjack** [comment]
closing as I checked and I also assume this worked on your end too

**Comment by canadaduane** [comment]
Yes, it works well, thanks!
